services:
  web:
    platform: linux/arm64/v8
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ./basic:/app
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - yii2-network

  db:
    platform: linux/arm64/v8
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=docker_php
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - "./basic/database:/docker-entrypoint-initdb.d"
      - yii2_mysql_data:/var/lib/mysql
    networks:
      - yii2-network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - 8002:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
      - yii2-network

networks:
  yii2-network:
    driver: bridge

volumes:
  yii2_mysql_data:
    name: yii2_mysql_data